definitions:
  controllers_swagger.AuthSignupBadResponse:
    properties:
      message:
        example: string
        type: string
      succeed:
        example: false
        type: boolean
    type: object
  controllers_swagger.AuthSignupConfirmOtpBadResponse:
    properties:
      message:
        example: string
        type: string
      succeed:
        example: false
        type: boolean
      token:
        example: ""
        type: string
    type: object
  controllers_swagger.GetAllUsersBadResponse:
    properties:
      message:
        example: Bad Request
        type: string
      succeed:
        example: false
        type: boolean
    type: object
  controllers_swagger.GetCurrentUserBadResponse:
    properties:
      message:
        example: string
        type: string
      succeed:
        example: false
        type: boolean
      user:
        example: "null"
        type: string
    type: object
  dtos.AuthSignupConfirmOtpRequest:
    properties:
      otpCode:
        example: "1234"
        type: string
      phoneNumber:
        example: "09123456789"
        maxLength: 11
        minLength: 11
        type: string
    required:
    - phoneNumber
    type: object
  dtos.AuthSignupRequest:
    properties:
      phoneNumber:
        example: "09123456789"
        maxLength: 11
        minLength: 11
        type: string
    required:
    - phoneNumber
    type: object
  dtos.AuthSignupResponse:
    properties:
      message:
        example: string
        type: string
      succeed:
        example: true
        type: boolean
    type: object
  dtos.AuthTokenResponse:
    properties:
      message:
        example: Succeed
        type: string
      succeed:
        example: true
        type: boolean
      token:
        example: the token will be here
        type: string
    type: object
  dtos.GetAllUsersResponse:
    properties:
      message:
        example: Succeed
        type: string
      page:
        example: 1
        type: integer
      pageSize:
        example: 10
        type: integer
      succeed:
        example: true
        type: boolean
      totalCount:
        example: 100
        type: integer
      totalPages:
        example: 10
        type: integer
      users:
        items:
          $ref: '#/definitions/models.User'
        type: array
    type: object
  dtos.GetCurrentUserResponse:
    properties:
      message:
        example: Succeed
        type: string
      succeed:
        example: true
        type: boolean
      user:
        $ref: '#/definitions/models.User'
    type: object
  models.User:
    properties:
      createdDate:
        example: "2025-08-12T19:53:35.685Z"
        type: string
      id:
        example: 689b9bbf5800ec55229e240b
        type: string
      phoneNumber:
        example: "09123456789"
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Sends an OTP code to the phoneNumber (fake OTP, just printed in
        the console)
      parameters:
      - description: AuthSignupRequest model
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dtos.AuthSignupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.AuthSignupResponse'
        "400":
          description: Request body is not valid
          schema:
            $ref: '#/definitions/controllers_swagger.AuthSignupBadResponse'
      summary: Signup Method
  /auth/signup/confirm-otp:
    post:
      consumes:
      - application/json
      description: Validate the PhoneNumber with the OtpCode alongside withit
      parameters:
      - description: AuthSignupConfirmOtpRequest model
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dtos.AuthSignupConfirmOtpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.AuthTokenResponse'
        "400":
          description: Request body is not valid
          schema:
            $ref: '#/definitions/controllers_swagger.AuthSignupConfirmOtpBadResponse'
      summary: Signup Confirm Otp Method
  /user:
    get:
      consumes:
      - application/json
      description: Get Current User Data using Jwt Token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.GetCurrentUserResponse'
        "400":
          description: Something Unknown Happend
          schema:
            $ref: '#/definitions/controllers_swagger.GetCurrentUserBadResponse'
      security:
      - ApiKeyAuth: []
      summary: Current User
  /user/{userId}:
    get:
      consumes:
      - application/json
      description: Get A User Data using Specified Id
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.GetCurrentUserResponse'
        "400":
          description: Something Unknown Happend
          schema:
            $ref: '#/definitions/controllers_swagger.GetCurrentUserBadResponse'
      security:
      - ApiKeyAuth: []
      summary: Get User By Id
  /user/all:
    get:
      consumes:
      - application/json
      description: Get all users with pagination and optional phone number search
      parameters:
      - description: 'Page number (default: 1)'
        in: query
        minimum: 1
        name: page
        type: integer
      - description: 'Page size (default: 10)'
        in: query
        maximum: 100
        minimum: 1
        name: pageSize
        type: integer
      - description: Phone number search (partial match)
        in: query
        name: phone
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.GetAllUsersResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers_swagger.GetAllUsersBadResponse'
      security:
      - ApiKeyAuth: []
      summary: Get All Users
securityDefinitions:
  ApiKeyAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
